name: auth_app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.5
  dio: ^5.4.0
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  get: ^4.7.2
  get_storage: ^2.1.1
  graphql: ^5.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1


flutter:
  uses-material-design: true
